### ISSUE TITLE
"Provide a valid public key" when trying to encrypt

### ISSUE THREAD

**Issue by wanshun123** [oraclize/encrypted-queries#2]
According to http://docs.oraclize.it/#ethereum-advanced-topics-encrypted-queries this command should encrypt "YOUR QUERY":

`python encrypted_queries_tools.py -e -p 044992e9473b7d90ca54d2886c7addd14a61109af202f1c95e218b0c99eb060c7134c4ae46345d0383ac996185762f04997d6fd6c393c86e4325c469741e64eca9 "YOUR QUERY"`

I get this error:

> C:\Python27\encrypted-queries-master\encrypted-queries-master\tools>python encrypted_queries_tools.py -e -p 044992e9473b7d90ca54d2886c7addd14a61109af202f1c95e218b0c99eb060c7134c4ae46345d0383ac996185762f04997d6fd6c393c86e4325c469741e64eca9 "YOUR QUERY"
>   File "encrypted_queries_tools.py", line 100
>     print "Please, provide a valid public key"

Is the public key given on the website incorrect?

**Comment by D-Nice** [comment]
Working fine here

```
python encrypted_queries_tools.py -e -p 044992e9473b7d90ca
54d2886c7addd14a61109af202f1c95e218b0c99eb060c7134c4ae46345d0383ac996185762f04997d6fd6c393c86e4325c469741e64eca9 "YOUR Q
UERY"
BMIsE080yO2JjzM/Mg16Ems8Aa1bnHEuAEfvz3OVU2D3sE6zDE/AeSI/NivzcP4MRV7KsdLsLbZQzZ9eEs11hZmsGCIGjuYEvVe6CPelOsN2LQoQ8nE2zQnP
XQ==
```

Ensure there isn't a newline character before the key parameter.

**Comment by wanshun123** [comment]
I have no idea what the issue is for me then as I'm running the command all on one line. And have tried copying and pasting your command (which is exactly the same of course) and still get the same error.

**Comment by wanshun123** [comment]
I am running Python 3.6.3rc1 - presumably that's the issue.

**Comment by wanshun123** [comment]
With Python 2.7.14 I get this error:

`Traceback (most recent call last):
  File "encrypted_queries_tools.py", line 5, in <module>
    from cryptography.hazmat.primitives import hashes
ImportError: No module named cryptography.hazmat.primitives`

Can you let me know what version of Python this is compatible with please.

**Comment by D-Nice** [comment]
Yes, the version you're running is relevant. I in fact ran it with Python 3, however, the script itself is made for Python 2. I recommend you use this utility to convert it to be compatible with 3: https://docs.python.org/2/library/2to3.html. Rechecking your earlier print error, that's the exact reason it failed in python 3, because the print statements are different in 2 and 3.

Otherwise, if you have missing modules, like cryptography, ensure they're installed with pip. Ideally it should work with python 2.7 without any need for conversion, as long as you have all required modules installed.
